# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 23:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA schema'),
        migrations.CreateModel(
            name='UnamanagedBarFoos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bar_foos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnmanagedBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnmanagedFoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'foo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"schema"."bar"',
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"schema"."foo"',
            },
        ),
        migrations.CreateModel(
            name='UnmanagedFooSubclass',
            fields=[
                ('unmanagedfoo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.UnmanagedFoo')),
            ],
            options={
                'db_table': 'foosubclass',
                'managed': False,
            },
            bases=('tests.unmanagedfoo',),
        ),
        migrations.CreateModel(
            name='FooSubclass',
            fields=[
                ('foo_ptr', models.OneToOneField(
                    auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False, to='tests.Foo', db_constraint=False)),
            ],
            options={
                'db_table': '"schema"."foosubclass"',
            },
            bases=('tests.foo',),
        ),
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bars', to='tests.Foo', db_constraint=False),
        ),
        migrations.AddField(
            model_name='bar',
            name='foos',
            field=models.ManyToManyField(db_table='"schema"."bar_foos"', related_name='m2m_bars', to='tests.Foo', db_constraint=False),
        ),
    ]
